[project]
authors = ["Joe Bacchus George <joebacchusgeorge@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "GNN_Heuristics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch_geometric = ">=2.5.3,<3"
pixi-pycharm = ">=0.0.8,<0.0.9"
dash = ">=2.18.2,<3"
dash-bootstrap-components = ">=1.6.0,<2"
diskcache = ">=5.6.3,<6"
multiprocess = ">=0.70.17,<0.71"
anyio = ">=4.7.0,<5"

[pypi-dependencies]
dash = { version = "*", extras = ["celery"] }

